// Generated by CoffeeScript 1.8.0
(function() {
  this.Clouds = (function() {
    Clouds.preload = function(game) {
      return game.load.image("cloud", "sprites/cloud.png");
    };

    function Clouds(game, player) {
      this.game = game;
      this.player = player;
    }

    Clouds.prototype.create_cloud = function(x, y) {
      var cloud;
      this.clouds = this.game.add.group();
      this.clouds.enableBody = true;
      cloud = this.clouds.create(x, y, "cloud");
      cloud.scale.setTo(2.0, 2.0);
      return cloud.body.velocity.x = -75;
    };

    Clouds.prototype.update = function() {
      return this.game.physics.arcade.overlap(this.player.sprite, this.clouds, function() {
        return console.log("Collision!!!!!!!!");
      });
    };

    return Clouds;

  })();

}).call(this);
