// Generated by CoffeeScript 1.8.0
(function() {
  this.GAME_HEIGHT = 600;

  this.GAME_WIDTH = 800;

  this.INCOMING_PLANE_VELOCITY = 300;

  this.CLOUD_VELOCITY = 75;

  this.SHAKE_VELOCITY = 10;

  this.SHAKE_HEIGHT = 20;

  this.LIGHTNING_TIME = 0.2;

  this.LIGHTNING_PROB = 2.0 / 60.0;

  this.LIGHTNING_DAMAGE = 3;

  this.CLOUD_SPAWN_X_EXTRA = 300;

  this.SCORE_PER_SECOND = 10;

  this.LEVEL1 = {
    time: 30,
    planes: 30,
    clouds: 40,
    f_lightning: 0.1,
    turbulence: 5
  };

  this.TIME_INCREASE = 5;

  this.PLANES_INCREASE = 10;

  this.CLOUDS_INCREASE = 10;

  this.F_LIGHTNING_INCREASE = 0.01;

  this.TURBULENCE_INCREASE = 10;

}).call(this);
