// Generated by CoffeeScript 1.8.0
(function() {
  this.GAME_HEIGHT = 600;

  this.GAME_WIDTH = 800;

  this.INCOMING_PLANE_VELOCITY = 300;

  this.CLOUD_VELOCITY = 75;

  this.SHAKE_VELOCITY = 10;

  this.SHAKE_HEIGHT = 20;

  this.LIGHTNING_TIME = 0.2;

  this.LIGHTNING_DAMAGE = 5;

}).call(this);
