// Generated by CoffeeScript 1.8.0
(function() {
  this.HealthBar = (function() {
    HealthBar.preload = function(game) {
      game.load.image("health_bar_back", "sprites/health_bar_background.png");
      return game.load.image("health_bar_front", "sprites/health_bar_front.png");
    };

    function HealthBar(game) {
      this.percentage = 100;
      this.game = game;
    }

    HealthBar.prototype.create = function(x, y) {
      this.back = this.game.add.image(x, y, "health_bar_back");
      return this.front = this.game.add.image(x, y, "health_bar_front");
    };

    HealthBar.prototype.set_percentage = function(percent) {
      this.percentage = percent;
      return this.front.scale.x = percent / 100;
    };

    return HealthBar;

  })();

}).call(this);
