// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.LevelComplete = (function() {
    function LevelComplete(game) {
      this.begin_next_level = __bind(this.begin_next_level, this);
    }

    LevelComplete.prototype.init = function(level_number) {
      return this.level_number = level_number;
    };

    LevelComplete.prototype.create = function() {
      var complete, next_level, style, text;
      style = {
        font: "100px Arial",
        fill: "rgb(0,0,0)",
        align: "center"
      };
      text = "Level " + this.level_number + " Complete";
      complete = this.game.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 - 100, text, style);
      complete.anchor.set(0.5);
      next_level = this.game.add.button(0, 300, "next_level", this.begin_next_level);
      return next_level.x = GAME_WIDTH / 2 - next_level.width / 2;
    };

    LevelComplete.prototype.begin_next_level = function() {
      return this.game.state.start("Game", true, false, this.level_number + 1);
    };

    return LevelComplete;

  })();

}).call(this);
