// Generated by CoffeeScript 1.8.0
(function() {
  this.LevelComplete = (function() {
    function LevelComplete(game) {}

    LevelComplete.prototype.init = function(level_number) {
      return this.level_number = level_number;
    };

    LevelComplete.prototype.create = function() {
      var complete, style, text;
      style = {
        font: "100px Arial",
        fill: "rgb(0,0,0)",
        align: "center"
      };
      text = "Level " + this.level_number + " Complete";
      complete = this.game.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 - 100, text, style);
      return complete.anchor.set(0.5);
    };

    return LevelComplete;

  })();

}).call(this);
