// Generated by CoffeeScript 1.8.0
(function() {
  this.GameOver = (function() {
    function GameOver(game) {}

    GameOver.prototype.init = function(score) {
      return this.score = score;
    };

    GameOver.prototype.create = function() {
      var game_over_text, play_again, score_style, score_text, style;
      style = {
        font: "76px Arial",
        fill: "rgb(0,0,0)",
        align: "center"
      };
      game_over_text = this.game.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 - 100, "Game Over", style);
      game_over_text.anchor.set(0.5);
      score_style = {
        font: "48px Arial",
        fill: "rgb(0, 0, 0)",
        align: "center"
      };
      score_text = this.game.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2, "Your Score: " + this.score, score_style);
      score_text.anchor.set(0.5);
      return play_again = this.game.add.button(GAME_WIDTH / 2 - 76, 350, "try_again", (function(_this) {
        return function() {
          return _this.game.state.start("Game", true, false, 1);
        };
      })(this));
    };

    return GameOver;

  })();

}).call(this);
