// Generated by CoffeeScript 1.8.0
(function() {
  var game,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.MainGame = (function() {
    function MainGame(game) {
      this.restart = __bind(this.restart, this);
    }

    MainGame.prototype.init = function(level) {
      return this.level = level;
    };

    MainGame.prototype.create = function() {
      var levels;
      this.health_bar = new HealthBar(this.game);
      this.player = new Player(this.game, this.health_bar);
      this.obstacles = new Obstacles(this.game, this.player, this.level);
      this.player.create(100, 100);
      this.obstacles.setup();
      levels = new Level(this.obstacles);
      levels.generate_level(this.level);
      return this.health_bar.create(GAME_WIDTH / 2, 20);
    };

    MainGame.prototype.update = function() {
      this.player.update();
      return this.obstacles.update();
    };

    MainGame.prototype.restart = function() {
      return this.game.state.start("Game", true, false, this.level);
    };

    return MainGame;

  })();

  game = new Phaser.Game(800, 600, Phaser.AUTO, "game");

  game.state.add("Boot", Boot);

  game.state.add("Preloader", Preloader);

  game.state.add("Menu", Menu);

  game.state.add("Credits", Credits);

  game.state.add("Game", MainGame);

  game.state.add("GameOver", GameOver);

  game.state.start("Boot");

}).call(this);
