// Generated by CoffeeScript 1.8.0
(function() {
  this.Menu = (function() {
    function Menu(game) {}

    Menu.prototype.preload = function() {
      this.game.load.image("button", "sprites/button.png");
      this.game.load.image("try_again", "sprites/try_again.png");
      return this.game.load.image("next_level", "sprites/next_level.png");
    };

    Menu.prototype.create = function() {
      var style, title;
      this.game.add.button(GAME_WIDTH / 2 - 76, 300, "button", this.on_play_now);
      this.game.stage.setBackgroundColor('rgb(135,206,250)');
      this.game.world.setBounds(0, 0, 2000, 2000);
      style = {
        font: "100px Arial",
        fill: "rgb(0,0,0)",
        align: "center"
      };
      title = this.game.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 - 100, "Flying Game", style);
      return title.anchor.set(0.5);
    };

    Menu.prototype.on_play_now = function() {
      return this.game.state.start("Game", true, false, 1);
    };

    return Menu;

  })();

}).call(this);
