// Generated by CoffeeScript 1.8.0
(function() {
  this.OncomingPlanes = (function() {
    OncomingPlanes.preload = function(game) {
      return game.load.image("oncoming_plane", "sprites/airplane_flipped.png");
    };

    function OncomingPlanes(game, player) {
      this.game = game;
      this.player = player;
    }

    OncomingPlanes.prototype.setup = function() {
      this.planes = this.game.add.group();
      return this.planes.enableBody = true;
    };

    OncomingPlanes.prototype.create_plane = function(x, y) {
      var plane;
      plane = this.planes.create(x, y, "oncoming_plane");
      return plane.body.velocity.x = -300;
    };

    OncomingPlanes.prototype.create_level = function(num_planes, x_start, x_end, y_start, y_end) {
      var i, x, y, _i, _results;
      _results = [];
      for (i = _i = 1; 1 <= num_planes ? _i <= num_planes : _i >= num_planes; i = 1 <= num_planes ? ++_i : --_i) {
        x = Math.random() * (x_end - x_start) + x_start;
        y = Math.random() * (y_end - y_start) + y_start;
        _results.push(this.create_plane(x, y));
      }
      return _results;
    };

    OncomingPlanes.prototype.update = function() {
      return this.game.physics.arcade.overlap(this.planes, this.player.sprite, function(player, plane) {
        plane.body.velocity.x = 0;
        player.body.velocity.y = 0;
        return player.alive = false;
      });
    };

    return OncomingPlanes;

  })();

}).call(this);
