// Generated by CoffeeScript 1.8.0
(function() {
  this.Player = (function() {
    function Player(game) {
      this.game = game;
      this.passenger_health = 100;
      this.passenger_happiness = 100;
    }

    Player.prototype.preload = function() {
      return game.load.image("player", "sprites/airplane_test.png");
    };

    Player.prototype.create = function() {
      return this.sprite = game.add.sprite(100, 100, "player");
    };

    return Player;

  })();

}).call(this);
