// Generated by CoffeeScript 1.8.0
(function() {
  this.Player = (function() {
    function Player(game) {
      this.game = game;
      this.passenger_health = 100;
      this.passenger_happiness = 100;
    }

    Player.prototype.preload = function() {
      return game.load.image("player", "sprites/airplane.png");
    };

    Player.prototype.create = function() {
      this.sprite = game.add.sprite(100, 100, "player");
      this.game.physics.arcade.enable(this.sprite);
      return this.sprite.body.collideWorldBounds = true;
    };

    Player.prototype.update = function() {
      var cursors;
      if (this.sprite.alive) {
        cursors = this.game.input.keyboard.createCursorKeys();
        if (cursors.up.isDown) {
          return this.sprite.body.velocity.y = -100;
        } else if (cursors.down.isDown) {
          return this.sprite.body.velocity.y = 100;
        } else {
          return this.sprite.body.velocity.y = 0;
        }
      }
    };

    return Player;

  })();

}).call(this);
