// Generated by CoffeeScript 1.8.0
(function() {
  this.Turbulence = (function() {
    function Turbulence(game) {
      this.game = game;
      this.positive = true;
    }

    Turbulence.prototype.shake = function() {
      var shake_velocity;
      shake_velocity = 10;
      if (this.positive) {
        if (this.game.camera.y === 20) {
          return this.positive = false;
        } else {
          return this.game.camera.y += shake_velocity;
        }
      } else {
        if (this.game.camera.y === 0) {
          return this.positive = true;
        } else {
          return this.game.camera.y -= shake_velocity;
        }
      }
    };

    return Turbulence;

  })();

}).call(this);
