// Generated by CoffeeScript 1.8.0
(function() {
  var create, game, preload, update;

  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });

  preload = function() {};

  create = function() {};

  update = function() {};

}).call(this);
