@GAME_HEIGHT = 600
@GAME_WIDTH = 800

@INCOMING_PLANE_VELOCITY = 300 # in pixels per second
@CLOUD_VELOCITY = 75
@SHAKE_VELOCITY = 10
@SHAKE_HEIGHT = 20
@LIGHTNING_TIME = 0.2 # in seconds

@LIGHTNING_DAMAGE = 5 # lightning damage per strike